name: Deploy to Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted   # matches my Pi runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using local compose on the Pi
        run: |
          echo "Runner: $(hostname) as $(whoami)"
          cd /srv/meme-search
          pwd
          ls -la
          docker compose pull
          docker compose up -d --build

      - name: Cleanup old images
        run: docker image prune -f
